import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Radio Caraibes FM",
            artist: "pop news talk sports",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-58.zeno.fm/54k0v7x14neuv?zs=X3sWFpLvQwyHjLVULjT9AQ",
            active: true,
        },
        {
            name:"Radio Mega Haiti",
            artist: "pop news talk sports",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://stream-25.zeno.fm/xugpr48vxxquv?zs=sQmPQHTkTK2kAfkcclSm5g",
            active: false,
        },
        {
            name:"Radio Tele Paradis",
            artist: "sports",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://stream-64.zeno.fm/nhak1rdw2ehvv?zs=gn9Mrws0QeWMVgLOXEZg7A",
            active: false,
        },
        {
            name:"Radio Kiskeya",
            artist: "pop news talk",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream-33.zeno.fm/82q102t62neuv?zs=Rmf-dhUlR3qIYHFWZk-R4Q",
            active: false,
        },
        {
            name:"Love A Child",
            artist: "christian children",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://ctntv.getstreamhosting.com:8028/creole",
            active: false,
        },
        {
            name:"Radio Ginen",
            artist: "pop news talk sports",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://stream-38.zeno.fm/83kabhy14neuv?zs=BCc13lgzTyujBK4I7PD4Rw",
            active: false,
        },
        {
            name:"Radio Magik9",
            artist: "pop talk",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "http://radiomagik9.primcast.com:7500/;stream.mp3",
            active: false,
        },
        {
            name:"mmradio HT",
            artist: "pop talk",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://stream-59.zeno.fm/3ksg75u0ng0uv?zs=V7gCUK57RZ-5HLqBwKnqBw",
            active: false,
        },
        {
            name:"Radio 4VEH",
            artist: "pop news talk sports",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-13.zeno.fm/0zef35h1my5tv?zs=qDw9s5FRQXG4bcHrBBW2gA",
            active: false,
        },
        {
            name:"Radio Evangelique la Voix de Dieu",
            artist: "christian gospel",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-24.zeno.fm/55znfebuchruv?zs=7nbrRIIzRsSMhgLnOBKZMw",
            active: false,
        },
        {
            name:"Univers FM",
            artist: "pop news talk sports",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-16.zeno.fm/7unxcs20vd0uv?zs=6-h2fp20QpqJLPKVcN6oLg",
            active: false,
        },
        {
            name:"Radio Shalom Haiti",
            artist: "christian contemporary",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-39.zeno.fm/krawcedmm4duv?zs=tKTc6fYfRdm7zlwJoNPhoA",
            active: false,
        },
        {
            name:"Chokarella Radio",
            artist: "pop news talk",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://streaming.radio.co/s97764d52b/listen",
            active: false,
        },
        {
            name:"Radio IBO",
            artist: "pop news talk",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-33.zeno.fm/ua1uavnxsv5tv?zs=hULNQm0xR0WgcZ0UQOib2Q",
            active: false,
        },
        {
            name:"La Voix de l'Esperance",
            artist: "christian contemporary",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-34.zeno.fm/cgnkcznsfvduv?zs=nATOrnmOQvaXk1h3ISnTyQ",
            active: false,
        },
        {
            name:"Alleluia FM",
            artist: "talk christian gospel",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-35.zeno.fm/usd1zxet69duv?zs=iyBwfXg-SXuQP1V-ubMGiA",
            active: false,
        },
        {
            name:"Radio Télé Vibe Kompa",
            artist: "classic rock zouk",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-43.zeno.fm/rsfcpyca32quv?zs=TZ7pyUiOSiaIc0ydO5GObw",
            active: false,
        },
        {
            name:"Impact FM",
            artist: "haitian",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://centova72.instainternet.com/proxy/impactfm?mp=/stream&DIST=TuneIn&TGT=TuneIn&maxServers=2&gdpr=0&us_privacy=1YNY&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzNDg4NTA5NiwiaXNzIjoidG",
            active: false,
        },
        {
            name:"Radio-Haiti-Fusion",
            artist: "caribbean zouk",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://ec3.yesstreaming.net:2500/stream",
            active: false,
        },
        {
            name:"Radio Miracle Port au Prince Haiti",
            artist: "christian",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "http://s6.voscast.com:9782/;",
            active: false,
        },
        {
            name:"Radio Ideal FM Haiti",
            artist: "pop news talk",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-57.zeno.fm/0naec4y686duv?zs=8xTFBRoZRe2swIWA0s248g",
            active: false,
        },
        {
            name:"RFM Haiti",
            artist: "pop talk",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-56.zeno.fm/na6d4xd5d4duv?zs=vmxOESAES6-nRZTM0Gvx5A",
            active: false,
        },
        {
            name:"Radio Tapinozet",
            artist: "reggae merengue zouk",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-55.zeno.fm/nte7q35dfkeuv?zs=cxIA8f1LT9-3DG302GWBfA",
            active: false,
        },
        {
            name:"Radio Tele Boston",
            artist: "pop news talk sports",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-51.zeno.fm/akccmbqu1ceuv?zs=R9XS6IRzRjm0FdZrf2-77g",
            active: false,
        },
        {
            name:"Radio Tout9",
            artist: "r'n'b rap reggae african merengue",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-40.zeno.fm/92v410r85wquv?zs=-KpnAncMRWGK_SMYKh_EIQ",
            active: false,
        },
        {
            name:"Radio-Fan",
            artist: "sports culture education politics",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-47.zeno.fm/x62mrzknwmzuv?zs=CfXk3VPnTMaDvPyc3H85IA",
            active: false,
        },
        {
            name:"Radio Miroir Inter (RMI)",
            artist: "pop news talk sports",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-55.zeno.fm/xt89a05tt5quv?zs=kfWcIk8-S16qDAxS-TiLOA",
            active: false,
        },
        {
            name:"Radio Émancipation FM",
            artist: "rock pop news reggae sports culture caribbean",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-26.zeno.fm/6rtd8uaf28quv?zs=EHcD3roaQ7u-POYGyAmO7Q",
            active: false,
        },
        {
            name:"Radio Tele Mega Star",
            artist: "pop news",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-40.zeno.fm/drtsun2aed0uv?zs=t8nRc37RS5u9hxLQgWMLOA",
            active: false,
        },
        {
            name:"Radio Tele Paradis",
            artist: "sports",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-64.zeno.fm/nhak1rdw2ehvv?zs=LeJ_skWPRA6EjTpsSey-LA",
            active: false,
        },
        {
            name:"Radio Tele Nativite Internationale",
            artist: "news sports haitian",
            cover: "https://m.media-amazon.com/images/I/91OYSpCaZDL._AC_UL320_.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream-31.zeno.fm/3mfrsnck65quv?zs=zq1UVQoRScCJ1_vNZjlQjA",
            active: false,
        },
        
        
    ];
}

export default chillHop;


